"""Write a design-space wiki to disk: markdown pages, the same pages as HTML, and a graph page.

Layout (docs/DESIGN_SPACE_EXPLORATION.md §13.2)::

    <out>/
    ├── .llmwiki.yaml, SCHEMA.md, raw/run.json
    ├── wiki/<shelf>/<slug>.md       markdown + YAML frontmatter + [[wikilinks]]
    └── html/<shelf>/<slug>.html     the same pages, plus graph.html and assets/

Everything opens from ``file://``: links are relative, d3 is vendored, and the
graph data is inlined in ``graph.html``.
"""

from __future__ import annotations

import html as html_lib
import importlib.resources
import json
import os
import posixpath
import re
import shutil
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping

import yaml
from jinja2 import Environment, FileSystemLoader, select_autoescape
from markdown_it import MarkdownIt

from taxonomy_generator.wiki.model import SYNTHESIS_ORDER, Export, Page

WIKILINK = re.compile(r"\[\[([^\]|]+)(?:\|([^\]]+))?\]\]")
# Same order as the index page: dimensions (with their values), synthesis, systems, sources; design points last.
SHELVES = [("concepts", "Dimensions"), ("entities", "Values"), ("synthesis", "Synthesis"),
           ("synthesis/systems", "Systems"), ("sources", "Sources"), ("designs", "Design points")]


def shelf_of(path: str) -> str:
    """Navigation group of a page path (system pages form their own group)."""
    return "synthesis/systems" if path.startswith("synthesis/systems/") else path.split("/")[0]
TEMPLATES = Path(__file__).resolve().parent / "templates"


# ── markdown ─────────────────────────────────────────────────────────────

def frontmatter_text(fm: Mapping[str, Any]) -> str:
    return yaml.safe_dump(dict(fm), sort_keys=False, allow_unicode=True, width=1000).strip()


def page_markdown(page: Page) -> str:
    return f"---\n{frontmatter_text(page.frontmatter)}\n---\n\n{page.body}"


SCHEMA = """# Design-space wiki: how this folder is organized

Generated by Delve's exporter from one run; do not edit by hand (rebuild instead).
Every page is rendered from the run's data, never written or reworded by an LLM.

- `wiki/index.md`: the run, its use case, and links to everything.
- `wiki/concepts/`: dimensions. Each is one design decision (decision point); its values are listed with status.
- `wiki/entities/`: dimension values (candidate decisions and outcomes). Status: `accepted`, `rejected`, `mixed` (both stances in the sources) or
  `outcome` (an effect of decisions, not a choice). Evidence lists the supporting passages and their stance.
- `wiki/sources/`: corpus sources and the decisions each informs.
- `wiki/synthesis/`: overview (use case, run summary, narrative summary), contested decisions, dropped dimensions;
  with a passage → system map, one page per system and the system × dimension matrix; with design points, the
  design-points overview; with `--evaluation`, the evaluation of the taxonomy.
- `wiki/designs/`: sampled design points (only when the export was given design points).
- `html/`: the same pages as HTML, and `html/graph.html`, an interactive graph of the design space.
- `raw/run.json`: the input files and settings of this export.

Frontmatter fields (`type`, `status`, `dimension`, `accepted_by`, `rejected_by`, `systems`, `design_points`) are the
queryable properties; `[[wikilinks]]` connect the pages. Cite passage ids (e.g. `s01_p10`) when answering from this wiki.
"""


def write_markdown(export: Export, out: Path, name: str) -> None:
    wiki = out / "wiki"
    for page in export.pages:
        path = wiki / f"{page.path}.md"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(page_markdown(page), encoding="utf-8")
    (out / ".llmwiki.yaml").write_text(
        yaml.safe_dump({"name": name, "domain": "design-space",
                        "paths": {"raw": "raw", "wiki": "wiki", "schema": "SCHEMA.md"}}, sort_keys=False),
        encoding="utf-8")
    (out / "SCHEMA.md").write_text(SCHEMA, encoding="utf-8")
    (out / "raw").mkdir(exist_ok=True)
    (out / "raw" / "run.json").write_text(json.dumps(export.manifest, indent=2, ensure_ascii=False) + "\n",
                                          encoding="utf-8")


# ── html ─────────────────────────────────────────────────────────────────

def html_file(path: str) -> str:
    return f"{path}.html"


def rel(from_path: str, to_file: str) -> str:
    """Relative URL from the HTML page of ``from_path`` to ``to_file`` (both under html/)."""
    start = posixpath.dirname(html_file(from_path)) or "."
    return posixpath.relpath(to_file, start)


def links_to_markdown(text: str, from_path: str, known: Iterable[str]) -> str:
    """Turn [[path|label]] into relative markdown links to the .html pages (unknown targets become plain text)."""
    known = set(known)

    def sub(m: re.Match) -> str:
        target, label = m.group(1).strip(), (m.group(2) or m.group(1)).strip()
        label = label.replace("[", "(").replace("]", ")")
        if target not in known:
            return label
        return f"[{label}]({rel(from_path, html_file(target))})"

    return WIKILINK.sub(sub, text)


CELL_LIST = re.compile(r"<td>(• .*?)</td>", re.S)


def cell_lists(html: str) -> str:
    """Table cells written as '• a<br>• b' become bulleted lists (the <br> arrives escaped)."""
    def sub(m: re.Match) -> str:
        entries = [e.strip()[2:].strip() if e.strip().startswith("•") else e.strip()
                   for e in m.group(1).split("&lt;br&gt;")]
        return "<td><ul class=\"cell-list\">" + "".join(f"<li>{e}</li>" for e in entries if e) + "</ul></td>"
    return CELL_LIST.sub(sub, html)


def _md() -> MarkdownIt:
    return MarkdownIt("commonmark", {"html": False, "linkify": False}).enable("table")


def property_rows(page: Page, known: Iterable[str]) -> List[Dict[str, str]]:
    """Frontmatter as (key, html value) rows; wikilinks become anchors."""
    md = _md()
    rows = []
    for key, value in page.frontmatter.items():
        if key in ("title", "tags", "core") or value in (None, "", [], {}):
            continue
        if isinstance(value, dict):
            text = ", ".join(f"{k}: {v}" for k, v in value.items() if v is not None)
        elif isinstance(value, list):
            text = ", ".join(str(v) for v in value)
        else:
            text = str(value)
        if key == "url" and text.startswith(("http://", "https://")):
            text = f"<{text}>"  # clickable
        rendered = md.renderInline(links_to_markdown(text, page.path, known))
        rows.append({"key": key.replace("_", " "), "value": rendered, "raw": str(value) if key == "status" else ""})
    return rows


def _env() -> Environment:
    return Environment(loader=FileSystemLoader(str(TEMPLATES)), autoescape=select_autoescape(["html", "j2"]),
                       trim_blocks=True, lstrip_blocks=True, keep_trailing_newline=True)


def _nav_key(page: Page):
    """Synthesis pages in their fixed (index) order; everything else alphabetical."""
    if page.path in SYNTHESIS_ORDER:
        return (SYNTHESIS_ORDER.index(page.path), "")
    return (len(SYNTHESIS_ORDER), page.title.lower())


def nav(export: Export, current: Page) -> List[Dict[str, Any]]:
    shelves = []
    for shelf, label in SHELVES:
        pages = [p for p in export.pages if shelf_of(p.path) == shelf]
        if not pages:
            continue
        shelves.append({"label": label, "open": shelf_of(current.path) == shelf,
                        "items": [{"title": ("★ " if p.frontmatter.get("core") else "") + p.title,
                                   "href": rel(current.path, html_file(p.path)),
                                   "status": p.frontmatter.get("status", ""), "current": p.path == current.path}
                                  for p in sorted(pages, key=_nav_key)]})
    return shelves


# Display sizes written into the exported SVGs, so every viewer (browser, VS Code
# preview, Obsidian) shows them small even without the stylesheet.
IMAGE_SIZES = {"delvedspace-logo.svg": (220, 64), "delvedspace-icon.svg": (32, 32), "case-icon.svg": (32, 32)}


def sized_svg(text: str, width: int, height: int) -> str:
    """Set the root <svg> width/height (keeping its viewBox, so it scales instead of cropping)."""
    m = re.search(r"<svg\b[^>]*>", text)
    if not m:
        return text
    tag = re.sub(r'\s(?:width|height)="[^"]*"', "", m.group(0))
    close = "/>" if tag.endswith("/>") else ">"
    tag = tag[:-len(close)].rstrip() + f' width="{width}" height="{height}"{close}'
    return text[:m.start()] + tag + text[m.end():]


def copy_images(assets: Path, case_icon: Path | None) -> None:
    assets.mkdir(parents=True, exist_ok=True)
    sources = {"delvedspace-logo.svg": TEMPLATES / "delvedspace-logo.svg",
               "delvedspace-icon.svg": TEMPLATES / "delvedspace-icon.svg"}
    if case_icon:
        sources["case-icon.svg"] = Path(case_icon)
    for name, src in sources.items():
        (assets / name).write_text(sized_svg(src.read_text(encoding="utf-8"), *IMAGE_SIZES[name]), encoding="utf-8")
    shutil.copyfile(TEMPLATES / "delve-pipeline.svg", assets / "delve-pipeline.svg")


def write_html(export: Export, out: Path, name: str, graph_node_of: Mapping[str, str],
               case_icon: Path | None = None) -> None:
    root = out / "html"
    assets = root / "assets"
    copy_images(assets, case_icon)
    shutil.copyfile(TEMPLATES / "style.css", assets / "style.css")
    d3 = importlib.resources.files("taxonomy_generator") / "assets" / "d3.min.js"
    (assets / "d3.min.js").write_text(d3.read_text(encoding="utf-8"), encoding="utf-8")

    env = _env()
    page_tpl = env.get_template("page.html.j2")
    known = {p.path for p in export.pages}
    md = _md()
    paths = {p.path for p in export.pages}
    quick = [(label, path) for label, path in [("Overview", "synthesis/overview"), ("Contested", "synthesis/contested"),
                                                ("System matrix", "synthesis/system-matrix"),
                                                ("Design points", "synthesis/design-points"),
                                                ("Evaluation", "synthesis/evaluation"),
                                                ("Dropped", "synthesis/dropped")] if path in paths]
    for page in export.pages:
        body = re.sub(r"\A# [^\n]*\n+", "", page.body)  # the title is rendered by the template
        body_html = cell_lists(md.render(links_to_markdown(body, page.path, known)))
        target = root / html_file(page.path)
        target.parent.mkdir(parents=True, exist_ok=True)
        node = graph_node_of.get(page.path)
        target.write_text(page_tpl.render(
            name=name, page=page, body=body_html, properties=property_rows(page, known),
            tags=page.frontmatter.get("tags") or [], nav=nav(export, page),
            css=rel(page.path, "assets/style.css"), home=rel(page.path, "index.html"),
            icon=rel(page.path, "assets/delvedspace-icon.svg"),
            case_icon=rel(page.path, "assets/case-icon.svg") if case_icon else "",
            graph=rel(page.path, "graph.html") + (f"#node={node}" if node else ""),
            tree=rel(page.path, "tree.html"),
            quick=[{"label": l, "href": rel(page.path, html_file(p))} for l, p in quick],
            approach=rel(page.path, "approach.html"),
            status=page.frontmatter.get("status", "")), encoding="utf-8")

    def tree_hrefs(node: Dict[str, Any]) -> Dict[str, Any]:
        return {**node, "href": html_file(node["href"]),
                "children": [tree_hrefs(c) for c in node.get("children") or []]}

    (root / "tree.html").write_text(env.get_template("tree.html.j2").render(
        name=name, data=json.dumps(tree_hrefs(export.tree), ensure_ascii=False).replace("</", "<\\/"),
        has_case_icon=bool(case_icon)), encoding="utf-8")

    graph = {"nodes": [{**n, "href": html_file(n["href"])} for n in export.graph["nodes"]],
             "edges": export.graph["edges"]}
    kinds = sorted({n["kind"] for n in graph["nodes"]})
    (root / "graph.html").write_text(env.get_template("graph.html.j2").render(
        name=name, data=json.dumps(graph, ensure_ascii=False, sort_keys=True).replace("</", "<\\/"),
        has_designs="design" in kinds, has_systems="system" in kinds, has_case_icon=bool(case_icon)),
        encoding="utf-8")


def write(export: Export, out: Path, name: str, case_icon: Path | None = None) -> None:
    """Write the whole export (replacing ``wiki/`` and ``html/`` from a previous export of the same run).

    ``case_icon`` (an SVG) is shown on the index and next to the wiki name; the
    DelveDSpace logo and icon are always included.
    """
    out = Path(out)
    for sub in ("wiki", "html"):
        if (out / sub).exists():
            shutil.rmtree(out / sub)
    out.mkdir(parents=True, exist_ok=True)
    write_markdown(export, out, name)
    copy_images(out / "wiki" / "assets", case_icon)
    graph_node_of = {n["href"]: n["id"] for n in export.graph["nodes"]}
    write_html(export, out, name, graph_node_of, case_icon)
